[package]
name = "vigemclient-sys"
version = "0.1.0"
authors = ["Yaroslav Isakov <yaroslav.isakov@gmail.com>"]
edition = "2018"
links = "ViGEmClient"

[dependencies]

[build-dependencies]
bindgen = "0.52"
cc = "1.0"
